#!/bin/bash

# 默认Test库
host="127.0.0.1"
user="root"
port="3306"
password=""
dbname="test"

WH=$1
if [ ${WH}x == ""x ]; then
    echo -e "\033[0mTest\033[0m environment......"
elif [ ${WH} == "Onle" ]; then
    # 线上库
    host=""
    user=""
    port=""
    password=""
    dbname=""
    echo -e "\033[0mOnle\033[0m environment......"
else 
    echo -e "\033[41;36mUsage:\033[0m Sql \033[36m[test|Onle|Other]\033[0m"
    echo -e "       \033[32mSql = Sql test\033[0m"
    exit
fi
mysql -h${host} -u${user} -P${port} -p${password} -D${dbname} --default-character-set=utf8
